apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dq3e2n13j-java-quarkus 
  janus-idp.io/tekton: dq3e2n13j-java-quarkus
  backstage.io/kubernetes-id: dq3e2n13j-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dq3e2n13j-java-quarkus
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  